const colors = {
  background: '#f0f0f7',
  primaryLighter: '#9871f5',
  primaryLight: '#916bea',
  primary: '#8257e5',
  primaryDark: '#774dd6',
  primaryDarker: '#6842c2',
  secondary: '#04d361',
  secondaryDark: '#04bf58',
  titleInPrimary: '#ffffff',
  textInPrimary: '#d4c2ff',
  textInPrimaryComplement: '#A380F6',
  textPlaceholder: '#c1bccc',
  textTitle: '#32264d',
  textComplement: '#9c98a6',
  textBase: '#6a6180',
  hoverBack: '#ebebf5',
  lineInWhite: '#e6e6f0',
  inputBackground: '#f8f8fc',
  buttonText: '#ffffff',
  boxBase: '#ffffff',
  boxFooter: '#fafafc',
};

export const {
  background,
  primaryLighter,
  primaryLight,
  primary,
  primaryDark,
  primaryDarker,
  secondary,
  secondaryDark,
  titleInPrimary,
  textInPrimary,
  textInPrimaryComplement,
  textPlaceholder,
  textTitle,
  textComplement,
  textBase,
  hoverBack,
  lineInWhite,
  inputBackground,
  buttonText,
  boxBase,
  boxFooter,
} = colors;
